Login check db file
arturogonzalezp/codeu_project_2017 pull request #6
Opened 2017-03-28 06:32 UTC by arturogonzalezp

Created all the code for login with the text inputs and check in the database.

- If a user is already in the server model it returns that user, if not it creates the user in the model.
- Run the server: `sh compile_and_run_server.sh`.
- Run the client: `sh compile_and_run_chat.sh SERVER_IP_ADDRESS`, if you are testing in the same computer you can use `sh compile_and_run_chat.sh localhost`.

2017-03-28 17:28 UTC, raguirre reviewed
Just the same recurring question about having all those variables as final. But other than that it looks good so far!

2017-03-28 17:28 UTC, raguirre commented on src/codeu/chat/client/ClientUser.java
> +    return (prev != current);
We can probably drop the parenthesis, not a big deal though.

2017-03-28 17:28 UTC, raguirre commented on src/codeu/chat/client/ClientUser.java
> +    final User prev = current;
Do we need prev to be final?

2017-03-28 17:28 UTC, raguirre commented on src/codeu/chat/client/maingui/MainGui.java
> +    final User loginUser = clientContext.user.checkUserInDatabase(username, pswd);
Do we need loginUser to be final?

2017-03-28 17:28 UTC, raguirre commented on src/codeu/chat/databases/users
> +[
I don't think we should track the database in the repository

2017-03-28 17:28 UTC, raguirre commented on src/codeu/chat/server/Controller.java
> +    try (BufferedReader br = new BufferedReader(new FileReader("../src/codeu/chat/databases/users"))) {
Maybe we should create a constant variable to store the database location

2017-03-28 17:28 UTC, raguirre commented on src/codeu/chat/server/Controller.java
> +          LOG.info("User created and logged in (user.id=%s user.name=%s user.display_name=%s user.time=%s)",user.id,user.name,user.display_name,user.creation);
We can maybe create a User.toString() method to avoid having this long string here

2017-03-28 17:28 UTC, raguirre commented on src/codeu/chat/server/Server.java
> +      final User user = controller.searchUserInDatabase(username, pswd);
Same question about using the final keyword

2017-03-28 18:38 UTC, arturogonzalezp commented on src/codeu/chat/client/ClientUser.java
> +    final User prev = current;
Because the prev should not change. Google has an example in the same class.

2017-03-28 18:38 UTC, arturogonzalezp commented on src/codeu/chat/client/ClientUser.java
> +    return (prev != current);
That is an example of another class function.

2017-03-28 18:38 UTC, heyimcesar commented on src/codeu/chat/client/maingui/MainGui.java
> +    final User loginUser = clientContext.user.checkUserInDatabase(username, pswd);
Yes, in order to make it safe and not to change during the request

2017-03-28 18:39 UTC, arturogonzalezp commented on src/codeu/chat/server/Controller.java
> +    try (BufferedReader br = new BufferedReader(new FileReader("../src/codeu/chat/databases/users"))) {
I've considered it and it would be a nice implementation to have a static class to save all the paths of databases.

2017-03-28 18:40 UTC, arturogonzalezp commented on src/codeu/chat/server/Controller.java
> +          LOG.info("User created and logged in (user.id=%s user.name=%s user.display_name=%s user.time=%s)",user.id,user.name,user.display_name,user.creation);
It already has a "toString()" form but that code was implemented by google, not by me. I only used it.

2017-03-28 18:41 UTC, arturogonzalezp commented on src/codeu/chat/server/Server.java
> +      final User user = controller.searchUserInDatabase(username, pswd);
To avoid changes in the variable, every request should not change the user.

2017-03-28 18:43 UTC, arturogonzalezp commented
@raguirre thanks for the review, It should be very useful to have the class that has all the databases paths.

2017-03-28 23:56 UTC, raguirre commented
I would like to see what @wilph thinks about keeping track of the database file in the repo, and the inclusion of the gson.jar library file (which I missed in my original review).

My suggestion would be removing the database file and creating a .gitignore file, then adding the db  file to it.

2017-03-29 02:40 UTC, YoaliSB approved these changes

2017-03-29 02:40 UTC, YoaliSB approved these changes

2017-03-29 16:02 UTC, wilph commented on src/codeu/chat/client/ClientUser.java
> +
nit -- revert if this newline wasn't purposeful

2017-03-29 21:47 UTC, raguirre requested changes
Please change the db file and leave only the minimum amount of users to seed a new project. Then, add the gitignore file to avoid tracking new changes to the file. You may need to so this in two separate commits.

2017-04-26 04:32 UTC, closed without merging